name: Scoreboards-Test
author: Frantisek Novosad (iamceph) <frantisek@nvsd.dev>
version: ${project.version}
api-version: 1.13
website: https://hryozivot.net
main: org.screamingsandals.lib.scoreboards.test.Test