site_name: ScreamingLib
site_url: http://localhost:8000

theme:
  name: material
  custom_dir: ./overrides
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    # - navigation.tabs
  palette:
    - scheme: slate
      primary: cyan
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: cyan
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ScreamingSandals
    - icon: fontawesome/brands/discord
      link: https://screamingsandals.org/discord
  version:
    provider: mike
    default: latest

copyright: Copyright &copy; 2021 ScreamingSandals

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true

edit_uri: ""
repo_url: https://github.com/ScreamingSandals/ScreamingLib
repo_name: ScreamingSandals/ScreamingLib

plugins:
  - git-revision-date:
      enabled_if_env: CI
  - search

nav:
  - Home: index.md
  - Modules:
    - Core: modules/core.md
    - Event: modules/event.md
    - Plugin: modules/plugin.md
    - Tasker: modules/tasker.md
    - Command: modules/command.md
    - NPC: modules/npc.md
    - Packets: modules/packets.md
  - NMSMapper: nmsmapper.md
