sourceSets {
    support_1_20_1 {
        java {
        }
    }

    main {
        compileClasspath += support_1_20_1.output
        output.dir(support_1_20_1.output.classesDirs, builtBy: "compileSupport_1_20_1Java")
    }
}

dependencies {
    compileOnly libs.paper
    support_1_20_1CompileOnly libs.paper.support.one.twenty.one
}

if (tasks.findByName("sourceJar")) {
    tasks.named("sourceJar") {
        sourceSets.matching { it.name != 'test' }.each {
            from it.allJava
        }
    }
}