def supportVersions = [
    '1_21_3': libs.paper.support.one.twentyone.three,
    '1_21_1': libs.paper.support.one.twentyone.one,
    '1_20_6': libs.paper.support.one.twenty.six,
    '1_20_1': libs.paper.support.one.twenty.one,
    '1_12_2': libs.paper.support.one.twelve.two,
    '1_8_8': libs.paper.support.one.eight.eight,

    'datafixer2': libs.datafixerupper2,
]

sourceSets {
    common {
        java {
        }
    }

    for (def ver : supportVersions.keySet()) {
        "support_${ver}" {
            compileClasspath += sourceSets.common.output

            java {
            }
        }

        main {
            compileClasspath += sourceSets."support_${ver}".output
            output.dir(sourceSets."support_${ver}".output.classesDirs, builtBy: "compileSupport_${ver}Java")
        }
    }
}

configurations {
    mainCompileOnly {
    }

    commonCompileOnly {
        extendsFrom(mainCompileOnly)
        extendsFrom(compileOnly)
        extendsFrom(api)
    }

    for (def ver : supportVersions.keySet()) {
        it."support_${ver}CompileOnly" {
            extendsFrom(compileOnly)
            extendsFrom(api)
        }
    }

    stubs {
        extendsFrom(compileOnly)
        extendsFrom(api)
    }
}

sourceSets {
    main {
        compileClasspath += configurations.mainCompileOnly + sourceSets.common.output
        output.dir(sourceSets.common.output.classesDirs, builtBy: 'compileCommonJava')
    }
}

dependencies {
    api project(':nms'), {
        targetConfiguration = 'shadow'
    }

    api project(':paperlib'), {
        targetConfiguration = 'shadow'
    }
    api project(':spectator-adventure')
    api project(':spectator-bungee')

    mainCompileOnly libs.paper
    mainCompileOnly libs.datafixerupper
    for (def ver : supportVersions) {
        "support_${ver.key}CompileOnly" ver.value
    }

    compileOnly libs.netty
    compileOnly libs.viaversion
    compileOnly libs.protocolsupport
}

if (tasks.findByName("sourceJar")) {
    tasks.named("sourceJar") {
        sourceSets.matching { it.name != 'test' }.each {
            from it.allJava
        }
    }
}