name: Build and deploy ScreamingLib docs
on: push
concurrency: slib_docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: bash publish.sh