name: Build and publish ScreamingLib

on:
  push:
    branches: [ ver/2.0.x ]

concurrency: slib_build

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean checkLicenses build --stacktrace --warning-mode all
    - name: Publish with Gradle
      run: ./gradlew publish --stacktrace --warning-mode all
      env:
        NEXUS_URL_RELEASE: ${{ secrets.NEXUS_URL_RELEASE }}
        NEXUS_URL_SNAPSHOT: ${{ secrets.NEXUS_URL_SNAPSHOT }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      # TODO: javadoc building and publishing

